# Generated by Django 3.1.3 on 2020-11-04 14:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(choices=[('Pcs', 'Packages'), ('Ltr', 'Liter'), ('Kg', 'Kilogram')], max_length=255)),
                ('price', models.IntegerField()),
                ('stocks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.TextField()),
                ('balance', models.IntegerField()),
                ('barcode_enter', models.TextField()),
                ('barcode_payment', models.TextField()),
                ('barcode_exit', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('foto', models.ImageField(upload_to='uploads/foto/756b5a2c-d0ca-4f95-a768-9eb833a6680a/')),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.CharField(max_length=8)),
                ('total', models.IntegerField()),
                ('time', models.DateTimeField(default=datetime.datetime(2020, 11, 4, 14, 4, 52, 847467, tzinfo=utc))),
                ('merchants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cashier.merchant')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cashier.user')),
            ],
        ),
        migrations.CreateModel(
            name='SubTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cashier.item')),
                ('transactions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cashier.transaction')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='merchants',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cashier.merchant'),
        ),
        migrations.CreateModel(
            name='ExitHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime(2020, 11, 4, 14, 4, 52, 847467, tzinfo=utc))),
                ('merchants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cashier.merchant')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cashier.user')),
            ],
        ),
        migrations.CreateModel(
            name='EnterHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime(2020, 11, 4, 14, 4, 52, 847467, tzinfo=utc))),
                ('merchants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cashier.merchant')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cashier.user')),
            ],
        ),
    ]
