# Generated by Django 3.1.3 on 2020-11-04 20:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Cashier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='/uploads/items/default.png', upload_to='uploads/items/5e2febcc-4dd0-488a-8e5c-2f7f3d77e907/'),
        ),
        migrations.AlterField(
            model_name='enterhistory',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 4, 20, 38, 51, 292933, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='exithistory',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 4, 20, 38, 51, 292933, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 4, 20, 38, 51, 292933, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.ImageField(upload_to='uploads/foto/fd2b670b-925a-4b8a-b458-1696169304a8/'),
        ),
    ]
