# Generated by Django 3.1.3 on 2020-11-08 11:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Cashier', '0003_auto_20201108_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='note',
        ),
        migrations.AlterField(
            model_name='enterhistory',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 8, 10, 56, 35, 719685, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='exithistory',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 8, 10, 56, 35, 719685, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='/uploads/items/default.png', upload_to='uploads/items/d8eb9564-ac7b-43bd-86df-10172ced7aca/'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 8, 10, 56, 35, 719685, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.ImageField(default='/uploads/foto/default.png', upload_to='uploads/foto/2e2a7117-3812-4f70-add5-b085ea6689d9/'),
        ),
    ]
