# Generated by Django 3.1.3 on 2020-11-11 04:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Cashier', '0007_auto_20201110_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemainingCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterTime', models.DateTimeField(default=datetime.datetime(2020, 11, 11, 3, 53, 28, 80010, tzinfo=utc))),
                ('exitTime', models.DateTimeField(default=datetime.datetime(2020, 11, 11, 3, 53, 28, 80010, tzinfo=utc))),
                ('merchants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cashier.merchant')),
            ],
        ),
        migrations.RemoveField(
            model_name='exithistory',
            name='merchants',
        ),
        migrations.RemoveField(
            model_name='exithistory',
            name='users',
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='/uploads/items/default.png', upload_to='uploads/items/b8e374e0-a259-4866-b32b-5264ccb5d795/'),
        ),
        migrations.AlterField(
            model_name='topuphistory',
            name='record',
            field=models.CharField(default='957975D1', max_length=8),
        ),
        migrations.AlterField(
            model_name='topuphistory',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 3, 53, 28, 80010, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 3, 53, 28, 80010, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.ImageField(default='/uploads/foto/default.png', upload_to='uploads/foto/75c7a733-4da8-434d-aef2-507724ee8fda/'),
        ),
        migrations.DeleteModel(
            name='EnterHistory',
        ),
        migrations.DeleteModel(
            name='ExitHistory',
        ),
        migrations.AddField(
            model_name='remainingcustomer',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cashier.user'),
        ),
    ]
