# Generated by Django 3.1.3 on 2020-11-11 04:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Cashier', '0008_auto_20201111_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='/uploads/items/default.png', upload_to='uploads/items/65916e06-a84a-4ff2-b83e-b11aba7d7d0c/'),
        ),
        migrations.AlterField(
            model_name='remainingcustomer',
            name='enterTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 4, 26, 52, 976032, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='remainingcustomer',
            name='exitTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topuphistory',
            name='record',
            field=models.CharField(default='2B6C1165', max_length=8),
        ),
        migrations.AlterField(
            model_name='topuphistory',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 4, 26, 52, 976032, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 4, 26, 52, 976032, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.ImageField(default='/uploads/foto/default.png', upload_to='uploads/foto/528403e2-2c48-439f-a8a4-7ccb0113bf29/'),
        ),
    ]
