# Generated by Django 3.1.3 on 2020-11-11 07:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Cashier', '0010_auto_20201111_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='/uploads/items/default.png', upload_to='uploads/items/9f6e7033-5ba1-4375-b5ec-aacdfafe4e82/'),
        ),
        migrations.AlterField(
            model_name='remainingcustomer',
            name='enterTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 7, 17, 27, 942760, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='topuphistory',
            name='record',
            field=models.CharField(default='B366C0D0', max_length=8),
        ),
        migrations.AlterField(
            model_name='topuphistory',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 7, 17, 27, 942760, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 7, 17, 27, 942760, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.ImageField(default='/uploads/foto/default.png', upload_to='uploads/foto/e52918e3-eeb2-4c60-8d55-0644497b1947/'),
        ),
    ]
