# Generated by Django 3.1.3 on 2020-11-11 08:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Cashier', '0013_auto_20201111_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantbarcode',
            name='is_finish',
        ),
        migrations.AddField(
            model_name='remainingcustomer',
            name='is_enter',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='/uploads/items/default.png', upload_to='uploads/items/7d27343d-247f-4a4e-a665-28f40e4642d2/'),
        ),
        migrations.AlterField(
            model_name='remainingcustomer',
            name='enterTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 7, 58, 23, 849129, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='topuphistory',
            name='record',
            field=models.CharField(default='026F4FA8', max_length=8),
        ),
        migrations.AlterField(
            model_name='topuphistory',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 7, 58, 23, 849129, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 7, 58, 23, 849129, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.ImageField(default='/uploads/foto/default.png', upload_to='uploads/foto/afeb6a9d-fbec-4b73-8870-7d7aaf8e45c0/'),
        ),
    ]
