# Generated by Django 3.1.3 on 2020-11-12 09:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Cashier', '0016_auto_20201112_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantbarcode',
            name='transactions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cashier.transaction'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='/uploads/items/default.png', upload_to='uploads/items/4c9c0204-d107-4bad-b3a1-8bea73529bf1/'),
        ),
        migrations.AlterField(
            model_name='remainingcustomer',
            name='enterTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 9, 1, 32, 522214, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='topuphistory',
            name='record',
            field=models.CharField(default='355D684A', max_length=8),
        ),
        migrations.AlterField(
            model_name='topuphistory',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 9, 1, 32, 522214, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 9, 1, 32, 522214, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.ImageField(default='/uploads/foto/default.png', upload_to='uploads/foto/9759f3c6-709a-4f4f-8611-3b2d54acfed3/'),
        ),
    ]
